name: ToGateway

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .gitignore
      - README.md
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup deck
        uses: kong/setup-deck@v1
      - name: Setup inso
        uses: kong/setup-inso@v1 
        with:
          inso-version: v1.1.7
      - name: Export API spec
        run: inso -w $GITHUB_WORKSPACE export spec UUIDgen -o uuidgen.yaml --ci
      #- name: check source code
      #  run: inso lint spec
      #- name: run test suite
      #  run: inso run test spc_869ca3 --env env_6e24f55242
      - name: convert OAS to Kong gateway configuration
        run: deck file openapi2kong --spec uuidgen.yaml --output-file ./kong.yaml
      - name: Apply new configuration
        #run: deck sync --konnect-runtime-group-name se-wenhan-shi --konnect-token ${{ secrets.KONNECT_PERSONAL_TOKEN }} -s kong-new-3.0.yaml
        run: deck gateway sync --headers Kong-Admin-Token:test --workspace demo kong.yaml --tls-skip-verify
        env:
            DECK_KONG_ADDR: ${{ secrets.ADMIN_API_URL }}
