name: ToGateway

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .gitignore
      - .github
      - README.md
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "12"
      - name: Setup deck
        uses: kong/setup-deck@v1
      - name: Setup inso
        uses: kong/setup-inso@v1 
        with:
          inso-version: 10.1.1
      - name: check source code
        run: inso -w $GITHUB_WORKSPACE lint spec my-spec.yaml
      - name: run test suite
        run: inso -w $GITHUB_WORKSPACE run test uts_1b98a4 --env env_929fbe
      - name: Export API spec
        run: inso -w $GITHUB_WORKSPACE export spec spc -o uuidgen.yaml --ci
      - name: convert OAS to Kong gateway configuration
        run: deck file openapi2kong --spec uuidgen.yaml --output-file ./kong.yaml
      - name: Apply new configuration
        #run: deck sync --konnect-runtime-group-name se-wenhan-shi --konnect-token ${{ secrets.KONNECT_PERSONAL_TOKEN }} -s kong-new-3.0.yaml
        run: deck gateway sync --headers Kong-Admin-Token:test --workspace demo kong.yaml --tls-skip-verify
        env:
            DECK_KONG_ADDR: ${{ secrets.ADMIN_API_URL }}
